/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AgentsToolsNewRouteImport } from './routes/agents.tools.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsToolsNewRoute = AgentsToolsNewRouteImport.update({
  id: '/tools/new',
  path: '/tools/new',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/agents/tools/new': typeof AgentsToolsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/agents': typeof AgentsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/agents/tools/new': typeof AgentsToolsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/agents/tools/new': typeof AgentsToolsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/integrations'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/campaigns/$id'
    | '/agents/'
    | '/campaigns/'
    | '/agents/tools/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/integrations'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/campaigns/$id'
    | '/agents'
    | '/campaigns'
    | '/agents/tools/new'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/integrations'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/campaigns/$id'
    | '/agents/'
    | '/campaigns/'
    | '/agents/tools/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/tools/new': {
      id: '/agents/tools/new'
      path: '/tools/new'
      fullPath: '/agents/tools/new'
      preLoaderRoute: typeof AgentsToolsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentsToolsNewRoute: typeof AgentsToolsNewRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AgentsToolsNewRoute: AgentsToolsNewRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
